name: Test

on: [create]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - run: npm ci
    - run: npm run build

    - name: Zip Release
      id: zip_release
      uses: ./
      with:
        path: release.zip
        include: lib/

    - uses: actions/upload-artifact@v1
      with:
        name: result
        path: release.zip